# Generated by cucumber-sinatra. (Thu Jun 03 14:45:47 -0400 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

World do
  Capybara.default_selector = :css
  Capybara.app = SkeletonApp
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

Before do
  DataMapper.auto_migrate!
end
